# Generated by Django 3.0.6 on 2020-05-25 06:51

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import saleor.core.utils.json_serializer


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0045_auto_20200427_0425'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0117_auto_20200423_0737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('rrule', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('upcoming_order_creation_date', models.DateTimeField(null=True)),
                ('upcoming_delivery_date', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], default='draft', max_length=32)),
                ('token', models.CharField(blank=True, max_length=36, unique=True)),
                ('customer_note', models.TextField(blank=True, default='')),
                ('ended_with_reason', models.TextField(blank=True, default='')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('billing_address', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='account.Address')),
                ('shipping_address', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='account.Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.ProductVariant')),
            ],
            options={
                'ordering': ('-pk',),
                'permissions': (('manage_subscriptions', 'Manage subscriptions.'),),
            },
        ),
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('type', models.CharField(choices=[('DRAFT_CREATED', 'draft_created'), ('ACTIVATED', 'activated'), ('RECURRENCE_RULE_UPDATED', 'recurrence_rule_updated'), ('START_DATE_UPDATED', 'start_date_updated'), ('SHIPPING_ADDRESS_UPDATED', 'shipping_address_updated'), ('PRODUCT_QUANTITY_UPDATED', 'product_quantity_updated'), ('PAUSED', 'paused'), ('ENDED', 'ended'), ('NOTIFICATION_SENT', 'notification_sent'), ('NOTE_ADDED', 'note_added'), ('OTHER', 'other')], max_length=255)),
                ('parameters', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='subscription.Subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
