# Generated by Django 2.2.10 on 2020-05-01 18:30

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0015_auto_20200203_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.NullBooleanField(editable=False)),
                ('currency', models.CharField(default='INR', editable=False, max_length=3)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.NullBooleanField(editable=False)),
                ('transaction_type', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], db_index=True, max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('ledger_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('source', models.CharField(max_length=40)),
                ('reason', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='wallet.Wallet')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='WalletRecharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('initiated', 'initiated'), ('payment_created', 'payment_created'), ('abandoned', 'abandoned'), ('failed', 'failed'), ('successful', 'successful')], db_index=True, default='initiated', max_length=40)),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.Payment')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_recharges', to='wallet.Wallet')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
